name: Test
version: '${version}'
main: com.iroom.test.Test
api-version: 1.16
commands:
  safestop:
    description: 데이터를 저장하고 서버를 종료
    usage: /safestop
  safesave:
    description: 데이터를 저장
    usage: /safesave
  shop:
    description: 상점 아이템을 줌
    usage: /shop