name: Economy
version: '${version}'
main: com.iroom.economy.Economy
api-version: 1.16
depend: [ Kotlin ]
commands:
  safestop:
    description: 데이터를 저장하고 서버를 종료
    usage: /safestop
  safesave:
    description: 데이터를 저장
    usage: /safesave
  shop:
    description: 상점 아이템을 줌
    usage: /shop